"""
civicqa.auditor
===============

The CivicQAAuditor runs all ISO/IEC 5259 data-quality dimensions over a
dataset and produces an explainable, AI-Act-aligned audit report.

The report is designed to satisfy EU AI Act expectations for high-risk AI:
  - Article 10 (data governance / quality of training data)
  - Article 12 (record-keeping / traceable logging)

Usage:
    from civicqa import CivicQAAuditor
    auditor = CivicQAAuditor()
    report = auditor.audit(df, config={...})
    report.to_json("audit.json")
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Optional
import datetime as _dt
import json

import pandas as pd

from .dimensions import ALL_DIMENSIONS, DimensionResult

__version__ = "0.1.0"


@dataclass
class AuditReport:
    dataset_name: str
    timestamp: str
    overall_score: float
    grade: str
    dimensions: list[dict]
    summary_issues: list[str]
    record_count: int
    column_count: int
    tool_version: str = __version__
    iso_basis: str = "ISO/IEC 5259 (data quality for analytics and ML)"
    ai_act_alignment: list[str] = field(default_factory=lambda: [
        "EU AI Act Article 10 — data governance and quality",
        "EU AI Act Article 12 — record-keeping and traceability",
    ])

    def as_dict(self) -> dict[str, Any]:
        return {
            "civicqa_audit": {
                "tool_version": self.tool_version,
                "iso_basis": self.iso_basis,
                "ai_act_alignment": self.ai_act_alignment,
                "dataset": {
                    "name": self.dataset_name,
                    "records": self.record_count,
                    "columns": self.column_count,
                },
                "timestamp": self.timestamp,
                "result": {
                    "overall_score": round(self.overall_score, 4),
                    "grade": self.grade,
                },
                "dimensions": self.dimensions,
                "summary_issues": self.summary_issues,
            }
        }

    def to_json(self, path: Optional[str] = None, indent: int = 2) -> str:
        text = json.dumps(self.as_dict(), indent=indent, default=str)
        if path:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(text)
        return text

    def to_markdown(self) -> str:
        lines = [
            f"# CivicQA Data-Quality Audit — {self.dataset_name}",
            "",
            f"- **Overall score:** {self.overall_score:.1%}  (**{self.grade}**)",
            f"- **Records / columns:** {self.record_count} / {self.column_count}",
            f"- **Audited:** {self.timestamp}",
            f"- **Basis:** {self.iso_basis}",
            "",
            "## Dimension scores",
            "",
            "| Dimension | Score | ISO reference |",
            "|-----------|-------|---------------|",
        ]
        for d in self.dimensions:
            lines.append(f"| {d['dimension']} | {d['score']:.0%} | {d['iso_reference']} |")
        if self.summary_issues:
            lines += ["", "## Key issues", ""]
            lines += [f"- {issue}" for issue in self.summary_issues]
        else:
            lines += ["", "_No significant issues detected._"]
        lines += ["", f"_Generated by CivicQA Auditor v{self.tool_version}._"]
        return "\n".join(lines)


def _grade(score: float) -> str:
    if score >= 0.90:
        return "A — excellent"
    if score >= 0.75:
        return "B — good"
    if score >= 0.60:
        return "C — adequate"
    if score >= 0.40:
        return "D — weak"
    return "E — inadequate"


class CivicQAAuditor:
    """
    Runs the full suite of ISO/IEC 5259 dimensions and produces an AuditReport.

    config keys (all optional):
        rules                  -> per-column accuracy rules (see dimensions.accuracy)
        date_column            -> column for currentness
        max_age_days           -> freshness threshold (default 365)
        protected_columns      -> columns for representativeness
        reference_distribution -> per-attribute reference shares (e.g. census)
        metadata               -> {title, description, columns} for accessibility
    """

    def __init__(self, dimensions=None):
        self.dimensions = dimensions or ALL_DIMENSIONS

    def audit(self, df: pd.DataFrame, dataset_name: str = "dataset",
              config: Optional[dict] = None) -> AuditReport:
        config = config or {}
        results: list[DimensionResult] = []
        for fn in self.dimensions:
            try:
                res = fn(df, **config)
            except Exception as exc:  # never let one dimension break the audit
                res = DimensionResult(
                    dimension=fn.__name__, score=0.0, weight=0.0,
                    evidence={"error": str(exc)},
                    issues=[f"Dimension '{fn.__name__}' failed: {exc}"],
                )
            results.append(res)

        # weighted composite (skip zero-weight / not-assessed dimensions)
        weighted = [(r.score, r.weight) for r in results if r.weight > 0]
        total_w = sum(w for _, w in weighted)
        overall = sum(s * w for s, w in weighted) / total_w if total_w else 0.0

        summary_issues: list[str] = []
        for r in results:
            summary_issues.extend(r.issues)

        return AuditReport(
            dataset_name=dataset_name,
            timestamp=_dt.datetime.now(tz=_dt.timezone.utc).isoformat(),
            overall_score=overall,
            grade=_grade(overall),
            dimensions=[r.as_dict() for r in results],
            summary_issues=summary_issues[:50],
            record_count=len(df),
            column_count=len(df.columns),
        )
